apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: modresorts-ingress
  namespace: modresorts
  labels:
    app: modresorts
    component: web
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/managed-certificates: ""
spec:
  rules:
    - host: modresorts.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: modresorts-service
                port:
                  number: 80
